repos:
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7
    args: ['--line-length=120']
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.16
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=2048']
  - id: flake8
